site_title: "Key4hep Reconstruction Validation"
organization: "FCC Collaboration"
footer_text: "Key4hep Reconstruction Validation"

detectors:
  - id: "IDEA"
    version: "IDEA_o1_v03"
    name: "IDEA Detector"
    description: "Innovative Detector for an Electron-positron Accelerator"

  - id: "ALLEGRO"
    version: "ALLEGRO_o1_v03"
    name: "ALLEGRO Detector"
    description: "A Lepton-Lepton collider Experiment with Granular Read-Out"

  - id: "CLD"
    version: "CLD_o2_v08"
    name: "CLD Detector"
    description: "CLIC-Like Detector"
